on: pull_request

name: '[DEBUG] Workflow context information'

jobs:
  hello_world:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo 'Hello World!'

  debug:
    name: Display workflow context information
    runs-on: ubuntu-latest
    needs: hello_world

    steps:
      - name: Hello World in steps
        id: hello_world_in_steps
        run: echo 'Hello World in steps!'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
